DROP TABLE IF EXISTS PAYMENT_METHOD;
DROP TABLE IF EXISTS TRANSACTION;
DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER (
  id INT AUTO_INCREMENT  PRIMARY KEY
);

CREATE TABLE PAYMENT_METHOD (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  type VARCHAR(250) NOT NULL,
  card_number VARCHAR(250) NOT NULL,
  expiryDate VARCHAR(250) NOT NULL,
  ccv TEXT DEFAULT NULL,
  foreign key (customer_id) references CUSTOMER(id)
);

CREATE TABLE TRANSACTION (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
);

CREATE TABLE TRANSACTION (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  price DECIMAL NOT NULL,
  quantity INTEGER NOT NULL,
  foreign key (customer_id) references CUSTOMER(id)
  foreign key (product_id) references PRODUCT(id)
);